// eslint-config-next ships flat config from v16, so the eslintrc compatibility
// layer this file used to need is gone.
import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const config = [
  ...coreWebVitals,
  ...typescript,
  // next-env.d.ts is generated by Next and is not ours to lint.
  { ignores: [".next/**", "node_modules/**", "out/**", "next-env.d.ts"] },
];

export default config;
